version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hrsoft_db
      POSTGRES_USER: hrsoft_user
      POSTGRES_PASSWORD: hrsoft_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hrsoft-network

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - hrsoft-network

  # Auth Service
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://hrsoft_user:hrsoft_password@postgres/hrsoft_db
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=auth-service
    depends_on:
      - postgres
      - redis
    networks:
      - hrsoft-network

  # User Service
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://hrsoft_user:hrsoft_password@postgres/hrsoft_db
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=user-service
      - AUTH_SERVICE_URL=http://auth-service:8000
    depends_on:
      - postgres
      - redis
      - auth-service
    networks:
      - hrsoft-network

  # Nginx Load Balancer
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - auth-service
      - user-service
    networks:
      - hrsoft-network

volumes:
  postgres_data:

networks:
  hrsoft-network:
    driver: bridge
